In [1]:
import cv2 as cv
import re
import os
import psycopg2
from scipy.misc import bytescale
import numpy as np

In [2]:
def writeContours(src, dest, name):
    
    try: 
        os.makedirs(dest)
    except OSError:
        if not os.path.isdir(dest):
            raise

    files = os.listdir(src);
    frames = sum(1 for file in files if file.endswith(".tif"))

    for i in range(frames):
        image = cv.imread(src + name + "{:03.0f}.tif".format(i))

        imgray = cv.cvtColor(image, cv.COLOR_BGR2GRAY)
        contours, hierarchy = cv.findContours(imgray, cv.RETR_EXTERNAL ,  cv.CHAIN_APPROX_NONE)
       
        os.mkdir(dest + str(i))
        for j in  range(len(contours)):
            if len(contours[j]) > 10:
                f= open(dest + str(i)+"\\"+str(j)+".wkt","w+")
                line = re.sub("[\[\]]", "", str(contours[j]))
                line = line.replace("\n\n", ",")
                f.write("POLYGON(("+line.strip()+"))\n")
                f.close()

In [3]:
src = "..\\Datasets\\TrackingChallenge\\Fluo-N2DH-SIM+\\02_GT\\TRA\\segmented\\0\\";
dest = src + "man_track\\";
name = "man_track";


writeContours(src,dest,name)

WindowsError: [Error 183] Impossível criar um ficheiro quando esse ficheiro já existe: '..\\Datasets\\TrackingChallenge\\Fluo-N2DH-SIM+\\02_GT\\TRA\\segmented\\0\\man_track\\0'

In [14]:
def LoadVideoFrames(pHost, pDatabase, pUser, pPwd,path):
    conn = None
    try:
   
        # connect to the PostgreSQL server
        print('Connecting to the PostgreSQL database...')
        conn = psycopg2.connect(host=pHost,port=5434,database=pDatabase, user=pUser, password=pPwd)
     
        # create a cursor
        cur = conn.cursor()
       
        # execute a statement
        print('PostgreSQL connected')
   
        #cur.execute("delete from mytable where name = '" + pObjectName + "'");
   
        allLines = []
        time = 0
       
        dirlist = os.listdir(path)
        for dir in dirlist:
            frameN = int(''.join(filter(str.isdigit, dir)));
            fileList = os.listdir(path+dir)
            for file in fileList:
                time = file.replace('.wkt', '').replace('interpolation', '')
            
                with open(path + dir+'/' + file) as f:
                    for line in f:
                        print line
                        print(path + dir+'/' + file)
                        lineTmp = line.split(',');
                        pol = line[:-3]+','+lineTmp[0][9:]+line[-3:];
                        if (line.startswith('POLYGON')):
                            command = "insert into lifetime values (%d,%d,ST_RotateX('%s',pi()))" % (int(time),frameN,pol);
                            #print (command)
                            cur.execute(command);
                        else:
                            print(time);

                   
         
        # close the communication with the PostgreSQL
        cur.close()
        conn.commit()
   
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
    finally:
        if conn is not None:
       
            conn.close()
            print('Database connection closed.')

In [16]:
host = "localhost";
database = "PhC-C2DL-PSC_ST";
user = "postgres";
pw = "postgres";
path ="..\\Datasets\\TrackingChallenge\\PhC-C2DL-PSC\\01_ST\\SEG\\segmented\\0\\man_track\\";



LoadVideoFrames(host,database,user,pw,path)

Connecting to the PostgreSQL database...
PostgreSQL connected
POLYGON((890 734, 889 735, 888 736, 887 737, 886 738, 885 738, 884 738, 883 739, 882 739, 881 739, 880 740, 879 740, 878 740, 877 740, 876 741, 875 741, 874 742, 873 743, 872 743, 871 743, 870 743, 869 743, 868 743, 867 743, 866 744, 865 745, 864 746, 863 747, 862 747, 861 748, 860 749, 859 750, 858 750, 857 751, 856 751, 855 752, 854 752, 853 753, 852 753, 851 753, 850 754, 849 755, 848 756, 847 756, 846 756, 845 757, 844 757, 843 758, 842 758, 841 758, 840 758, 839 759, 838 759, 837 760, 836 761, 835 762, 834 763, 833 764, 832 764, 832 765, 831 766, 830 767, 829 768, 828 768, 827 769, 826 770, 825 771, 824 772, 823 772, 822 773, 821 774, 820 775, 819 776, 818 777, 817 778, 816 778, 815 779, 814 779, 813 780, 812 781, 811 781, 810 782, 809 783, 808 784, 807 784, 806 785, 805 786, 804 787, 803 787, 802 788, 801 788, 800 788, 799 788, 798 788, 797 789, 796 789, 795 789, 794 790, 793 790, 792 790, 791 791, 790 791, 789 791, 788 791, 787 792, 786 792, 785 793, 784 793, 783 793, 782 794, 781 794, 780 794, 779 794, 778 794, 777 794, 776 794, 775 794, 774 794, 773 794, 772 794, 771 795, 770 795, 769 795, 768 795, 767 796, 766 796, 765 796, 764 796, 763 796, 762 796, 761 796, 760 795, 759 795, 758 795, 757 795, 756 795, 755 795, 754 795, 753 795, 752 795, 751 795, 750 795, 749 795, 748 795, 747 795, 746 795, 745 794, 744 794, 743 794, 742 794, 741 794, 740 794, 739 794, 738 794, 737 794, 736 794, 735 794, 734 794, 733 794, 732 794, 731 795, 730 795, 729 795, 728 796, 727 796, 726 796, 725 796, 724 796, 723 797, 723 798, 723 799, 724 800, 725 800, 726 800, 727 800, 728 800, 729 801, 730 801, 731 802, 731 803, 732 803, 733 804, 734 804, 735 804, 736 805, 737 805, 738 806, 739 806, 740 806, 741 806, 742 806, 743 806, 744 806, 745 806, 746 806, 747 807, 748 807, 749 807, 750 808, 751 809, 752 810, 753 810, 754 810, 755 810, 756 810, 757 810, 758 810, 759 810, 760 809, 761 809, 762 809, 763 809, 764 809, 765 808, 766 808, 767 808, 768 807, 769 807, 770 807, 771 806, 772 806, 773 805, 774 805, 775 804, 776 804, 777 803, 778 803, 779 803, 780 803, 781 803, 782 803, 783 803, 784 803, 785 803, 786 804, 787 804, 788 804, 789 805, 790 805, 791 805, 792 805, 793 805, 794 804, 795 804, 796 805, 797 805, 798 805, 799 805, 800 806, 801 806, 802 806, 803 807, 804 807, 805 808, 806 808, 807 808, 808 809, 809 809, 810 809, 811 809, 812 810, 813 811, 814 811, 815 812, 816 812, 817 812, 818 812, 819 813, 820 813, 821 813, 822 812, 823 812, 824 812, 825 812, 826 812, 827 813, 828 814, 829 814, 830 814, 831 814, 832 814, 833 814, 834 813, 835 813, 836 813, 837 812, 838 812, 838 811, 839 810, 840 810, 840 809, 841 808, 842 808, 842 807, 843 806, 844 805, 845 804, 846 803, 847 802, 848 802, 849 802, 850 801, 851 801, 852 801, 853 801, 854 801, 855 801, 856 801, 857 801, 858 801, 859 801, 860 800, 861 799, 862 798, 863 798, 864 798, 865 799, 866 799, 867 800, 868 801, 869 802, 869 803, 869 804, 870 805, 871 806, 872 806, 873 807, 874 807, 875 807, 876 808, 877 808, 878 808, 879 808, 880 807, 881 807, 882 806, 883 806, 884 806, 885 805, 886 804, 887 804, 888 805, 889 806, 890 806, 891 806, 892 805, 893 804, 894 804, 895 803, 896 803, 897 802, 896 801, 896 800, 896 799, 896 798, 895 797, 896 796, 896 795, 896 794, 896 793, 896 792, 896 791, 897 790, 897 789, 898 788, 899 788, 899 787, 900 786, 900 785, 901 784, 901 783, 902 782, 902 781, 903 780, 902 779, 902 778, 901 777, 901 776, 900 775, 900 774, 899 773, 898 772, 897 771, 896 770, 895 770, 894 769, 894 768, 893 767, 893 766, 893 765, 894 764, 894 763, 894 762, 895 761, 896 760, 896 759, 896 758, 896 757, 896 756, 896 755, 897 754, 897 753, 898 752, 898 751, 898 750, 898 749, 898 748, 898 747, 897 746, 897 745, 898 744, 897 743, 897 742, 897 741, 898 740, 898 739, 898 738, 897 737, 898 736, 899 736, 900 736, 899 736, 898 736, 897 736, 896 736, 895 736, 894 736, 893 736, 892 735, 892 734, 891 734))

..\Datasets\TrackingChallenge\DIC-C2DH-HeLa\01_ST\SEG\segmented\0\man_track\0/0.wkt
POLYGON((298 712, 297 713, 296 713, 295 713, 294 714, 293 715, 292 715, 291 716, 290 716, 289 716, 288 717, 287 717, 286 717, 285 717, 284 717, 283 717, 282 717, 281 717, 280 718, 279 718, 278 718, 277 718, 276 718, 275 719, 274 719, 273 719, 272 719, 271 719, 270 719, 269 720, 268 720, 267 720, 266 720, 265 720, 264 720, 263 720, 262 721, 261 721, 260 721, 259 721, 258 721, 257 721, 256 721, 255 721, 254 721, 253 721, 252 721, 251 721, 250 721, 249 721, 248 721, 247 722, 246 722, 245 722, 244 722, 243 722, 242 722, 241 722, 240 722, 239 722, 238 722, 237 723, 236 723, 235 724, 234 724, 233 725, 232 726, 231 726, 230 727, 229 727, 228 728, 227 728, 226 728, 225 729, 224 729, 223 730, 222 731, 221 731, 220 732, 219 732, 218 732, 217 733, 216 733, 215 733, 214 733, 213 734, 212 734, 211 734, 210 735, 209 735, 208 735, 207 735, 206 736, 205 736, 204 736, 203 736, 202 736, 201 737, 200 737, 199 737, 198 737, 197 737, 196 738, 195 738, 194 738, 193 738, 192 738, 191 739, 190 739, 189 740, 188 740, 187 741, 186 742, 185 742, 184 742, 183 743, 182 743, 181 743, 180 743, 179 743, 178 743, 177 743, 176 743, 175 743, 174 743, 173 743, 172 743, 171 743, 170 743, 169 743, 168 743, 167 743, 166 743, 165 742, 164 742, 163 741, 162 740, 161 739, 160 739, 159 739, 158 738, 157 738, 156 738, 155 738, 154 738, 153 738, 152 739, 151 739, 150 740, 150 741, 149 742, 149 743, 149 744, 149 745, 150 746, 150 747, 150 748, 150 749, 151 750, 151 751, 152 752, 153 753, 154 753, 155 753, 156 754, 157 754, 158 754, 159 754, 160 753, 161 753, 162 753, 163 752, 164 752, 165 752, 166 751, 167 751, 168 751, 169 751, 170 751, 171 751, 172 751, 173 752, 174 752, 175 752, 176 753, 177 753, 178 754, 179 754, 180 754, 181 754, 182 754, 183 754, 184 753, 185 753, 186 752, 187 752, 188 752, 189 752, 190 752, 191 752, 192 752, 193 752, 194 752, 195 752, 196 752, 197 752, 198 752, 199 752, 200 752, 201 752, 202 751, 203 751, 204 751, 205 751, 206 750, 207 750, 208 750, 209 750, 210 750, 211 749, 212 749, 213 749, 214 749, 215 749, 216 748, 217 748, 218 748, 219 748, 220 748, 221 748, 222 748, 223 747, 224 747, 225 747, 226 747, 227 747, 228 747, 229 747, 230 747, 231 747, 232 746, 233 746, 234 746, 235 746, 236 746, 237 745, 238 745, 239 745, 240 745, 241 745, 242 745, 243 745, 244 746, 245 746, 246 746, 247 746, 248 746, 249 746, 250 746, 251 746, 252 746, 253 746, 254 746, 255 746, 256 745, 257 745, 258 745, 259 745, 260 745, 261 745, 262 745, 263 745, 264 745, 265 745, 266 745, 267 745, 268 745, 269 745, 270 745, 271 744, 272 744, 273 744, 274 744, 275 744, 276 744, 277 744, 278 744, 279 743, 280 742, 281 741, 282 740, 283 739, 284 738, 285 737, 286 736, 287 735, 288 734, 289 733, 289 732, 290 731, 291 730, 292 729, 293 729, 294 729, 295 728, 296 728, 297 729, 298 729, 299 729, 300 729, 301 729, 302 728, 303 728, 304 727, 305 726, 306 725, 306 724, 307 723, 307 722, 307 721, 307 720, 307 719, 307 718, 307 717, 307 716, 306 715, 305 714, 304 713, 303 713, 302 713, 301 712, 300 712, 299 712))

..\Datasets\TrackingChallenge\DIC-C2DH-HeLa\01_ST\SEG\segmented\0\man_track\0/1.wkt
POLYGON((351 585, 350 586, 349 586, ..., 354 587, 353 586, 352 586))

..\Datasets\TrackingChallenge\DIC-C2DH-HeLa\01_ST\SEG\segmented\0\man_track\0/2.wkt
parse error - invalid geometry
LINE 1: insert into lifetime values (2,0,ST_RotateX('POLYGON((351 58...
                                                    ^
HINT:  "...((351 585, 350 586, 349 586, ..., 354" <-- parse error at position 44 within geometry

Database connection closed.

In [17]:
import psycopg2
import os
def LoadCells(pHost, pDatabase, pUser, pPwd, pObjectName):
    conn = None
    try:
   
        # connect to the PostgreSQL server
        print('Connecting to the PostgreSQL database...')
        conn = psycopg2.connect(host=pHost,port=5434,database=pDatabase, user=pUser, password=pPwd)
     
        # create a cursor
        cur = conn.cursor()
       
        # execute a statement
        print('PostgreSQL connected')
   
        #cur.execute("delete from mytable where name = '" + pObjectName + "'");

       
       
        with open('..\\Datasets\\TrackingChallenge\\Fluo-N2DL-HeLa\\01_GT\\TRA\\man_track.txt') as f:
                for line in f:
                    values = line.split()
                    print(values[0])
                    command = 'insert into cells VALUES (%d,%d,%d,%d)' % (int(values[0]),int(values[1]),int(values[2]),int(values[3]));
                    print (command)
                    cur.execute(command);
                   
         
        # close the communication with the PostgreSQL
        cur.close()
        conn.commit()
   
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
    finally:
        if conn is not None:
       
            conn.close()
            print('Database connection closed.')
 
LoadCells("localhost","Fluo-N2DL-HeLa_ST","postgres","postgres", "cells")

Connecting to the PostgreSQL database...
PostgreSQL connected
1
insert into cells VALUES (1,0,30,0)
8
insert into cells VALUES (8,31,91,1)
9
insert into cells VALUES (9,31,91,1)
10
insert into cells VALUES (10,0,4,0)
12
insert into cells VALUES (12,0,38,0)
14
insert into cells VALUES (14,39,91,12)
15
insert into cells VALUES (15,39,91,12)
16
insert into cells VALUES (16,0,22,0)
18
insert into cells VALUES (18,23,91,16)
19
insert into cells VALUES (19,23,91,16)
20
insert into cells VALUES (20,43,91,0)
21
insert into cells VALUES (21,63,91,0)
22
insert into cells VALUES (22,0,1,0)
23
insert into cells VALUES (23,3,3,0)
24
insert into cells VALUES (24,3,37,0)
25
insert into cells VALUES (25,0,3,0)
28
insert into cells VALUES (28,4,49,25)
29
insert into cells VALUES (29,4,48,25)
30
insert into cells VALUES (30,0,1,0)
32
insert into cells VALUES (32,2,39,30)
33
insert into cells VALUES (33,2,44,30)
35
insert into cells VALUES (35,91,91,0)
36
insert into cells VALUES (36,40,91,32)
37
insert into cells VALUES (37,40,90,32)
39
insert into cells VALUES (39,45,91,33)
40
insert into cells VALUES (40,45,91,33)
41
insert into cells VALUES (41,0,32,0)
43
insert into cells VALUES (43,33,91,41)
44
insert into cells VALUES (44,33,91,41)
45
insert into cells VALUES (45,49,91,29)
46
insert into cells VALUES (46,49,91,29)
48
insert into cells VALUES (48,50,91,28)
49
insert into cells VALUES (49,50,91,28)
50
insert into cells VALUES (50,0,91,0)
51
insert into cells VALUES (51,0,17,0)
53
insert into cells VALUES (53,18,91,51)
54
insert into cells VALUES (54,18,91,51)
55
insert into cells VALUES (55,0,22,0)
58
insert into cells VALUES (58,23,75,55)
59
insert into cells VALUES (59,23,88,55)
61
insert into cells VALUES (61,76,91,58)
62
insert into cells VALUES (62,76,91,58)
63
insert into cells VALUES (63,0,21,0)
65
insert into cells VALUES (65,22,66,63)
66
insert into cells VALUES (66,22,81,63)
68
insert into cells VALUES (68,67,91,65)
69
insert into cells VALUES (69,67,91,65)
71
insert into cells VALUES (71,82,91,66)
72
insert into cells VALUES (72,82,91,66)
74
insert into cells VALUES (74,89,91,59)
75
insert into cells VALUES (75,89,91,59)
76
insert into cells VALUES (76,0,12,0)
78
insert into cells VALUES (78,13,51,76)
79
insert into cells VALUES (79,13,50,76)
80
insert into cells VALUES (80,51,91,79)
82
insert into cells VALUES (82,51,91,79)
84
insert into cells VALUES (84,52,91,78)
85
insert into cells VALUES (85,52,91,78)
86
insert into cells VALUES (86,0,14,0)
88
insert into cells VALUES (88,15,84,86)
89
insert into cells VALUES (89,15,57,86)
91
insert into cells VALUES (91,58,90,89)
92
insert into cells VALUES (92,91,91,0)
93
insert into cells VALUES (93,58,91,89)
94
insert into cells VALUES (94,0,33,0)
96
insert into cells VALUES (96,34,91,94)
97
insert into cells VALUES (97,34,91,94)
98
insert into cells VALUES (98,0,30,0)
100
insert into cells VALUES (100,31,91,98)
101
insert into cells VALUES (101,31,91,98)
102
insert into cells VALUES (102,0,7,0)
104
insert into cells VALUES (104,8,48,102)
105
insert into cells VALUES (105,8,64,102)
107
insert into cells VALUES (107,49,91,104)
108
insert into cells VALUES (108,49,91,104)
110
insert into cells VALUES (110,65,91,105)
111
insert into cells VALUES (111,65,91,105)
112
insert into cells VALUES (112,0,4,0)
114
insert into cells VALUES (114,5,55,112)
115
insert into cells VALUES (115,5,51,112)
117
insert into cells VALUES (117,52,91,115)
118
insert into cells VALUES (118,52,91,115)
120
insert into cells VALUES (120,56,91,114)
121
insert into cells VALUES (121,56,91,114)
123
insert into cells VALUES (123,85,91,88)
124
insert into cells VALUES (124,85,91,88)
125
insert into cells VALUES (125,0,14,0)
127
insert into cells VALUES (127,15,69,125)
128
insert into cells VALUES (128,15,60,125)
130
insert into cells VALUES (130,61,62,128)
131
insert into cells VALUES (131,61,91,128)
132
insert into cells VALUES (132,65,91,0)
133
insert into cells VALUES (133,0,14,0)
135
insert into cells VALUES (135,15,91,133)
136
insert into cells VALUES (136,15,91,133)
137
insert into cells VALUES (137,0,25,0)
139
insert into cells VALUES (139,26,91,137)
140
insert into cells VALUES (140,26,91,137)
141
insert into cells VALUES (141,0,2,0)
143
insert into cells VALUES (143,3,37,141)
144
insert into cells VALUES (144,3,37,141)
146
insert into cells VALUES (146,38,91,144)
147
insert into cells VALUES (147,38,91,144)
149
insert into cells VALUES (149,38,91,143)
150
insert into cells VALUES (150,38,91,143)
151
insert into cells VALUES (151,0,5,0)
153
insert into cells VALUES (153,6,40,151)
154
insert into cells VALUES (154,6,41,151)
156
insert into cells VALUES (156,41,91,153)
157
insert into cells VALUES (157,41,91,153)
159
insert into cells VALUES (159,42,91,154)
160
insert into cells VALUES (160,42,91,154)
161
insert into cells VALUES (161,0,3,0)
163
insert into cells VALUES (163,4,44,161)
164
insert into cells VALUES (164,4,41,161)
167
insert into cells VALUES (167,42,91,164)
168
insert into cells VALUES (168,42,91,164)
169
insert into cells VALUES (169,0,20,0)
171
insert into cells VALUES (171,21,55,169)
172
insert into cells VALUES (172,21,91,169)
174
insert into cells VALUES (174,56,91,171)
175
insert into cells VALUES (175,56,91,171)
177
insert into cells VALUES (177,0,8,0)
179
insert into cells VALUES (179,9,43,177)
180
insert into cells VALUES (180,9,91,177)
182
insert into cells VALUES (182,44,91,179)
183
insert into cells VALUES (183,44,91,179)
185
insert into cells VALUES (185,49,91,0)
186
insert into cells VALUES (186,0,91,0)
188
insert into cells VALUES (188,10,17,0)
189
insert into cells VALUES (189,0,13,0)
190
insert into cells VALUES (190,36,51,0)
192
insert into cells VALUES (192,52,91,190)
193
insert into cells VALUES (193,52,91,190)
195
insert into cells VALUES (195,45,91,163)
196
insert into cells VALUES (196,45,91,163)
197
insert into cells VALUES (197,0,60,0)
199
insert into cells VALUES (199,34,91,0)
200
insert into cells VALUES (200,0,35,0)
202
insert into cells VALUES (202,36,91,200)
203
insert into cells VALUES (203,36,91,200)
204
insert into cells VALUES (204,0,10,0)
207
insert into cells VALUES (207,11,39,204)
208
insert into cells VALUES (208,40,91,207)
211
insert into cells VALUES (211,41,79,220)
212
insert into cells VALUES (212,41,82,220)
214
insert into cells VALUES (214,76,91,221)
215
insert into cells VALUES (215,76,91,221)
217
insert into cells VALUES (217,80,91,211)
218
insert into cells VALUES (218,80,91,211)
220
insert into cells VALUES (220,11,40,204)
221
insert into cells VALUES (221,40,75,207)
223
insert into cells VALUES (223,83,91,212)
224
insert into cells VALUES (224,83,91,212)
225
insert into cells VALUES (225,0,13,0)
227
insert into cells VALUES (227,14,47,225)
228
insert into cells VALUES (228,14,44,225)
230
insert into cells VALUES (230,45,81,228)
231
insert into cells VALUES (231,45,79,228)
233
insert into cells VALUES (233,48,90,227)
234
insert into cells VALUES (234,48,90,227)
238
insert into cells VALUES (238,91,91,234)
239
insert into cells VALUES (239,91,91,234)
241
insert into cells VALUES (241,91,91,233)
242
insert into cells VALUES (242,91,91,233)
244
insert into cells VALUES (244,80,91,231)
245
insert into cells VALUES (245,80,91,231)
247
insert into cells VALUES (247,82,91,230)
248
insert into cells VALUES (248,82,91,230)
257
insert into cells VALUES (257,0,12,0)
259
insert into cells VALUES (259,13,42,257)
260
insert into cells VALUES (260,13,45,257)
262
insert into cells VALUES (262,43,85,259)
263
insert into cells VALUES (263,43,91,259)
265
insert into cells VALUES (265,46,90,260)
266
insert into cells VALUES (266,46,91,260)
268
insert into cells VALUES (268,91,91,265)
269
insert into cells VALUES (269,91,91,265)
270
insert into cells VALUES (270,0,13,0)
272
insert into cells VALUES (272,14,49,270)
273
insert into cells VALUES (273,14,52,270)
275
insert into cells VALUES (275,50,91,272)
276
insert into cells VALUES (276,50,91,272)
278
insert into cells VALUES (278,53,91,273)
279
insert into cells VALUES (279,53,91,273)
280
insert into cells VALUES (280,86,91,262)
282
insert into cells VALUES (282,86,91,262)
284
insert into cells VALUES (284,0,10,0)
286
insert into cells VALUES (286,11,48,284)
287
insert into cells VALUES (287,11,42,284)
288
insert into cells VALUES (288,0,10,0)
290
insert into cells VALUES (290,11,40,288)
291
insert into cells VALUES (291,11,42,288)
293
insert into cells VALUES (293,41,91,290)
294
insert into cells VALUES (294,41,91,290)
296
insert into cells VALUES (296,43,91,287)
297
insert into cells VALUES (297,43,91,287)
299
insert into cells VALUES (299,43,91,291)
300
insert into cells VALUES (300,43,91,291)
302
insert into cells VALUES (302,91,91,0)
303
insert into cells VALUES (303,49,91,286)
304
insert into cells VALUES (304,49,90,286)
305
insert into cells VALUES (305,0,15,0)
307
insert into cells VALUES (307,16,60,305)
308
insert into cells VALUES (308,16,54,305)
310
insert into cells VALUES (310,55,91,308)
311
insert into cells VALUES (311,55,91,308)
313
insert into cells VALUES (313,61,91,307)
314
insert into cells VALUES (314,61,91,307)
315
insert into cells VALUES (315,0,12,0)
317
insert into cells VALUES (317,13,47,315)
318
insert into cells VALUES (318,13,56,315)
321
insert into cells VALUES (321,48,91,317)
322
insert into cells VALUES (322,48,91,317)
324
insert into cells VALUES (324,57,91,318)
325
insert into cells VALUES (325,57,91,318)
326
insert into cells VALUES (326,0,7,0)
328
insert into cells VALUES (328,8,39,326)
329
insert into cells VALUES (329,8,37,326)
331
insert into cells VALUES (331,38,91,329)
332
insert into cells VALUES (332,38,91,329)
333
insert into cells VALUES (333,0,6,0)
335
insert into cells VALUES (335,7,14,333)
336
insert into cells VALUES (336,7,41,333)
337
insert into cells VALUES (337,21,34,0)
340
insert into cells VALUES (340,78,91,380)
341
insert into cells VALUES (341,78,91,380)
343
insert into cells VALUES (343,40,91,328)
344
insert into cells VALUES (344,40,91,328)
346
insert into cells VALUES (346,42,84,336)
347
insert into cells VALUES (347,42,76,336)
349
insert into cells VALUES (349,77,91,347)
350
insert into cells VALUES (350,77,91,347)
351
insert into cells VALUES (351,75,76,0)
352
insert into cells VALUES (352,78,91,0)
353
insert into cells VALUES (353,0,28,0)
355
insert into cells VALUES (355,29,91,353)
356
insert into cells VALUES (356,29,80,353)
358
insert into cells VALUES (358,85,91,346)
359
insert into cells VALUES (359,85,91,346)
361
insert into cells VALUES (361,70,91,127)
362
insert into cells VALUES (362,70,91,127)
363
insert into cells VALUES (363,0,46,0)
364
insert into cells VALUES (364,47,55,0)
365
insert into cells VALUES (365,47,59,0)
366
insert into cells VALUES (366,0,37,0)
368
insert into cells VALUES (368,38,42,366)
369
insert into cells VALUES (369,38,46,366)
370
insert into cells VALUES (370,36,36,0)
371
insert into cells VALUES (371,38,88,0)
372
insert into cells VALUES (372,38,88,0)
373
insert into cells VALUES (373,91,91,0)
374
insert into cells VALUES (374,10,14,0)
375
insert into cells VALUES (375,17,24,0)
376
insert into cells VALUES (376,27,29,0)
377
insert into cells VALUES (377,35,35,0)
380
insert into cells VALUES (380,38,77,0)
381
insert into cells VALUES (381,17,17,0)
382
insert into cells VALUES (382,23,24,0)
383
insert into cells VALUES (383,25,36,0)
384
insert into cells VALUES (384,42,44,0)
385
insert into cells VALUES (385,50,52,0)
387
insert into cells VALUES (387,64,76,0)
388
insert into cells VALUES (388,64,66,0)
389
insert into cells VALUES (389,86,91,0)
Database connection closed.

In [ ]:
a = "adsafas"

In [ ]:
print a[:5]